# config/config.yaml
hydra:
  job_logging:
    root:
      level: INFO
  sweep:
    subdir: ${hydra.job.override_dirname}

GENERAL:
  seed: 42
  verbose: True

DATA:
  N: 40  # number of images in the training set
  dataset: "mnist"

QNN:
  device: "default.qubit"
  non_equivariance: 1

TRAINING:
  epochs: 40
  learning_rate: 0.01
