# config/config.yaml
hydra:
  job_logging:
    root:
      level: INFO
  sweep:
    subdir: ${hydra.job.override_dirname}

GENERAL:
  seed: 42
  dev: "cuda"
  verbose: True
  initialization_analysis: True

DATA:
  N: 160  # number of images in the training set
  dataset: "mnist"

QNN:
  device: "default.qubit"
  non_equivariance: 0
  p_err: 0

TRAINING:
  epochs: 40
  learning_rate: 0.01
