# config/config.yaml
hydra:
  job_logging:
    root:
      level: INFO
  sweep:
    subdir: ${hydra.job.override_dirname}

GENERAL:
  seed: 42
  dev: "cpu"
  verbose: True
  initialization_analysis: False

DATA:
  N: 20  # number of images in the training set
  dataset: "mnist"

QNN:
  device: "default.mixed"
  non_equivariance: 4
  p_err: 0.01

TRAINING:
  epochs: 40
  learning_rate: 0.05
