# config/config.yaml
defaults:
  - general: general
  - data: data
  - qnn: qnn
  - training: training

hydra:
  job_logging:
    root:
      level: INFO
  sweep:
    subdir: ${hydra.job.override_dirname}
