# config/config.yaml
hydra:
  job_logging:
    root:
      level: INFO
  sweep:
    subdir: ${hydra.job.override_dirname}

GENERAL:
  seed: 22
  verbose: True

DATA:
  N: 20   # numero di immagini di training

QNN:
  device: "default.qubit"
  non_equivariance: 1

TRAINING:
  epochs: 2
  learning_rate: 0.01
